version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"  # Specify the Python version here

sphinx:
  configuration: doc/conf.py

formats: all

conda:
  environment: doc/environment.yml

python:
    install:
        - method: pip
          path: .
