version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"  # Specify the Python version here

sphinx:
  configuration: doc/conf.py

formats: all

python:
    install:
        - method: pip
          path: .
        - requirements: docs/requirements.txt