name: lfpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - c-compiler
  - cxx-compiler
  - Cython
  - h5py
  - jupyter
  - lfpykit
  - numpy
  - MEAutility>=1.4.2
  - matplotlib
  - mpi4py
  - pytest
  - scipy
  - pip
  - pip:
    - neuron
