name: lfpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - scipy
  - matplotlib
  - Cython
  - h5py
  - neuron
  - gxx_linux-64
  - pytest
  - ipython
  - pip
  pip:
    - mpi4py
