package:
  name: lfpy
  version: {{ environ.get("GIT_STRING", "0.0.0_custom")|replace("v", "")|replace("-", "_") }}

source:
  git_rev:
  git_url: https://github.com/LFPy/LFPy.git

build:
    noarch: python
    script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - numpy {{ numpy }}
    - scipy
    - Cython
    - h5py
    - neuron
    - mpich
    - mpi4py
    - matplotlib
  run:
    - python
    - setuptools
    - pip
    - {{ pin_compatible('numpy') }}
    - scipy
    - Cython
    - h5py
    - neuron
    - mpi4py
    - matplotlib

test:
  source_files:
    - LFPy
  requires:
    - pytest
    - pytest-cov
    - coveralls
    - codecov
  imports:
    - LFPy
  commands:
    - coverage run --source LFPy/test/ -m py.test -s
    - coverage report
    - codecov

about:
  home: https://github.com/LFPy/LFPy/
  license: GPLv3
  license_file: LICENSE
